name: Java demo project 
run-name: Java demo project #${{ github.run_number}}

on: 
  push:
    branches: [main] 
    paths: 
      - sample_java_project/**
      - .github/workflows/java_demo.yml 
env:
  BUILD_NUMBER: ${{github.run_number}}
  PRO_DIR: sample_java_project

jobs:
  code-compile: 
    runs-on: Ubuntu 

    steps:
      - name: code checkout 
        uses: actions/checkout@v4 

      - name: setup java 
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: check Java version 
        run: java --version

      - name: build the project with maven
        run:  mvn -B package --file $/PRO_DIR/pom.xml


